// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Servidor.Datos;

#nullable disable

namespace Servidor.Migrations
{
    [DbContext(typeof(MonedaDbContext))]
    [Migration("20240809202038_TokenUsuario")]
    partial class TokenUsuario
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Servidor.Dominio.Alerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MonedaId")
                        .HasColumnType("integer");

                    b.Property<int>("Porcentaje")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MonedaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Alertas");
                });

            modelBuilder.Entity("Servidor.Dominio.Cotizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MonedaBaseId")
                        .HasColumnType("integer");

                    b.Property<int>("MonedaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("MonedaBaseId");

                    b.ToTable("Cotizaciones");
                });

            modelBuilder.Entity("Servidor.Dominio.Moneda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Monedas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "AED",
                            Nombre = "Dirham de los Emiratos Árabes Unidos"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "AFN",
                            Nombre = "Afghani afgano"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "ALL",
                            Nombre = "Lek albanés"
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "AMD",
                            Nombre = "Dram armenio"
                        },
                        new
                        {
                            Id = 5,
                            Codigo = "ANG",
                            Nombre = "Florín antillano neerlandés"
                        },
                        new
                        {
                            Id = 6,
                            Codigo = "AOA",
                            Nombre = "Kwanza angoleño"
                        },
                        new
                        {
                            Id = 7,
                            Codigo = "ARS",
                            Nombre = "Peso argentino"
                        },
                        new
                        {
                            Id = 8,
                            Codigo = "AUD",
                            Nombre = "Dólar australiano"
                        },
                        new
                        {
                            Id = 9,
                            Codigo = "AWG",
                            Nombre = "Florín arubeño"
                        },
                        new
                        {
                            Id = 10,
                            Codigo = "AZN",
                            Nombre = "Manat azerbaiyano"
                        },
                        new
                        {
                            Id = 11,
                            Codigo = "BAM",
                            Nombre = "Marco convertible de Bosnia-Herzegovina"
                        },
                        new
                        {
                            Id = 12,
                            Codigo = "BBD",
                            Nombre = "Dólar de Barbados"
                        },
                        new
                        {
                            Id = 13,
                            Codigo = "BDT",
                            Nombre = "Taka bangladesí"
                        },
                        new
                        {
                            Id = 14,
                            Codigo = "BGN",
                            Nombre = "Lev búlgaro"
                        },
                        new
                        {
                            Id = 15,
                            Codigo = "BHD",
                            Nombre = "Dinar bahreiní"
                        },
                        new
                        {
                            Id = 16,
                            Codigo = "BIF",
                            Nombre = "Franco burundés"
                        },
                        new
                        {
                            Id = 17,
                            Codigo = "BMD",
                            Nombre = "Dólar de Bermudas"
                        },
                        new
                        {
                            Id = 18,
                            Codigo = "BND",
                            Nombre = "Dólar de Brunei"
                        },
                        new
                        {
                            Id = 19,
                            Codigo = "BOB",
                            Nombre = "Boliviano"
                        },
                        new
                        {
                            Id = 20,
                            Codigo = "BRL",
                            Nombre = "Real brasileño"
                        },
                        new
                        {
                            Id = 21,
                            Codigo = "BSD",
                            Nombre = "Dólar bahameño"
                        },
                        new
                        {
                            Id = 22,
                            Codigo = "BTN",
                            Nombre = "Ngultrum butanés"
                        },
                        new
                        {
                            Id = 23,
                            Codigo = "BWP",
                            Nombre = "Pula de Botsuana"
                        },
                        new
                        {
                            Id = 24,
                            Codigo = "BYN",
                            Nombre = "Rublo bielorruso"
                        },
                        new
                        {
                            Id = 25,
                            Codigo = "BZD",
                            Nombre = "Dólar beliceño"
                        },
                        new
                        {
                            Id = 26,
                            Codigo = "CAD",
                            Nombre = "Dólar canadiense"
                        },
                        new
                        {
                            Id = 27,
                            Codigo = "CDF",
                            Nombre = "Franco congoleño"
                        },
                        new
                        {
                            Id = 28,
                            Codigo = "CHF",
                            Nombre = "Franco suizo"
                        },
                        new
                        {
                            Id = 29,
                            Codigo = "CLF",
                            Nombre = "Unidad de Fomento"
                        },
                        new
                        {
                            Id = 30,
                            Codigo = "CLP",
                            Nombre = "Peso chileno"
                        },
                        new
                        {
                            Id = 31,
                            Codigo = "CNY",
                            Nombre = "Yuan chino"
                        },
                        new
                        {
                            Id = 32,
                            Codigo = "COP",
                            Nombre = "Peso colombiano"
                        },
                        new
                        {
                            Id = 33,
                            Codigo = "CRC",
                            Nombre = "Colón costarricense"
                        },
                        new
                        {
                            Id = 34,
                            Codigo = "CUC",
                            Nombre = "Peso convertible cubano"
                        },
                        new
                        {
                            Id = 35,
                            Codigo = "CUP",
                            Nombre = "Peso cubano"
                        },
                        new
                        {
                            Id = 36,
                            Codigo = "CVE",
                            Nombre = "Escudo caboverdiano"
                        },
                        new
                        {
                            Id = 37,
                            Codigo = "CZK",
                            Nombre = "Corona checa"
                        },
                        new
                        {
                            Id = 38,
                            Codigo = "DJF",
                            Nombre = "Franco de Yibuti"
                        },
                        new
                        {
                            Id = 39,
                            Codigo = "DKK",
                            Nombre = "Corona danesa"
                        },
                        new
                        {
                            Id = 40,
                            Codigo = "DOP",
                            Nombre = "Peso dominicano"
                        },
                        new
                        {
                            Id = 41,
                            Codigo = "DZD",
                            Nombre = "Dinar argelino"
                        },
                        new
                        {
                            Id = 42,
                            Codigo = "EGP",
                            Nombre = "Libra egipcia"
                        },
                        new
                        {
                            Id = 43,
                            Codigo = "ERN",
                            Nombre = "'Nakfa eritrea"
                        },
                        new
                        {
                            Id = 44,
                            Codigo = "ETB",
                            Nombre = "Birr etíope"
                        },
                        new
                        {
                            Id = 45,
                            Codigo = "EUR",
                            Nombre = "Euro"
                        },
                        new
                        {
                            Id = 46,
                            Codigo = "FJD",
                            Nombre = "óDlar fiyiano"
                        },
                        new
                        {
                            Id = 47,
                            Codigo = "FKP",
                            Nombre = "Libra de las Islas Malvinas"
                        },
                        new
                        {
                            Id = 48,
                            Codigo = "GBP",
                            Nombre = "Libra esterlina británica"
                        },
                        new
                        {
                            Id = 49,
                            Codigo = "GEL",
                            Nombre = "Lari georgiano"
                        },
                        new
                        {
                            Id = 50,
                            Codigo = "GGP",
                            Nombre = "Libra de Guernsey"
                        },
                        new
                        {
                            Id = 51,
                            Codigo = "GHS",
                            Nombre = "Cedi ghanés"
                        },
                        new
                        {
                            Id = 52,
                            Codigo = "GIP",
                            Nombre = "Libra de Gibraltar"
                        },
                        new
                        {
                            Id = 53,
                            Codigo = "GMD",
                            Nombre = "Dalasi gambiano"
                        },
                        new
                        {
                            Id = 54,
                            Codigo = "GNF",
                            Nombre = "Franco guineano"
                        },
                        new
                        {
                            Id = 55,
                            Codigo = "GTQ",
                            Nombre = "Quetzal guatemalteco"
                        },
                        new
                        {
                            Id = 56,
                            Codigo = "GYD",
                            Nombre = "Dólar guyanés"
                        },
                        new
                        {
                            Id = 57,
                            Codigo = "HKD",
                            Nombre = "Dólar de Hong Kong"
                        },
                        new
                        {
                            Id = 58,
                            Codigo = "HNL",
                            Nombre = "Lempira hondureño"
                        },
                        new
                        {
                            Id = 59,
                            Codigo = "HRK",
                            Nombre = "Kuna croata"
                        },
                        new
                        {
                            Id = 60,
                            Codigo = "HTG",
                            Nombre = "Gourde haitiano"
                        },
                        new
                        {
                            Id = 61,
                            Codigo = "HUF",
                            Nombre = "Forint húngaro"
                        },
                        new
                        {
                            Id = 62,
                            Codigo = "IDR",
                            Nombre = "Rupia indonesia"
                        },
                        new
                        {
                            Id = 63,
                            Codigo = "ILS",
                            Nombre = "Nuevo séquel israelí"
                        },
                        new
                        {
                            Id = 64,
                            Codigo = "INR",
                            Nombre = "Rupia india"
                        },
                        new
                        {
                            Id = 65,
                            Codigo = "IQD",
                            Nombre = "Dinar iraquí"
                        },
                        new
                        {
                            Id = 66,
                            Codigo = "IRR",
                            Nombre = "Rial iraní"
                        },
                        new
                        {
                            Id = 67,
                            Codigo = "ISK",
                            Nombre = "Corona islandesa"
                        },
                        new
                        {
                            Id = 68,
                            Codigo = "JMD",
                            Nombre = "Dólar jamaiquino"
                        },
                        new
                        {
                            Id = 69,
                            Codigo = "JOD",
                            Nombre = "Dinar jordano"
                        },
                        new
                        {
                            Id = 70,
                            Codigo = "JPY",
                            Nombre = "Yen japonés"
                        },
                        new
                        {
                            Id = 71,
                            Codigo = "KES",
                            Nombre = "Chelín keniano"
                        },
                        new
                        {
                            Id = 72,
                            Codigo = "KGS",
                            Nombre = "Som kirguís"
                        },
                        new
                        {
                            Id = 73,
                            Codigo = "KHR",
                            Nombre = "Riel camboyano"
                        },
                        new
                        {
                            Id = 74,
                            Codigo = "KMF",
                            Nombre = "Franco comorense"
                        },
                        new
                        {
                            Id = 75,
                            Codigo = "KPW",
                            Nombre = "Won norcoreano"
                        },
                        new
                        {
                            Id = 76,
                            Codigo = "KRW",
                            Nombre = "Won surcoreano"
                        },
                        new
                        {
                            Id = 77,
                            Codigo = "KWD",
                            Nombre = "Dinar kuwaití"
                        },
                        new
                        {
                            Id = 78,
                            Codigo = "KYD",
                            Nombre = "Dólar de las Islas Caimán"
                        },
                        new
                        {
                            Id = 79,
                            Codigo = "KZT",
                            Nombre = "Tenge kazajo"
                        },
                        new
                        {
                            Id = 80,
                            Codigo = "LAK",
                            Nombre = "Kip laosiano"
                        },
                        new
                        {
                            Id = 81,
                            Codigo = "LBP",
                            Nombre = "Libra libanesa"
                        },
                        new
                        {
                            Id = 82,
                            Codigo = "LKR",
                            Nombre = "Rupia de Sri Lanka"
                        },
                        new
                        {
                            Id = 83,
                            Codigo = "LRD",
                            Nombre = "Dólar liberiano"
                        },
                        new
                        {
                            Id = 84,
                            Codigo = "LSL",
                            Nombre = "Loti de Lesoto"
                        },
                        new
                        {
                            Id = 85,
                            Codigo = "LYD",
                            Nombre = "Dinar libio"
                        },
                        new
                        {
                            Id = 86,
                            Codigo = "MAD",
                            Nombre = "Dirham marroquí"
                        },
                        new
                        {
                            Id = 87,
                            Codigo = "MDL",
                            Nombre = "Leu moldavo"
                        },
                        new
                        {
                            Id = 88,
                            Codigo = "MGA",
                            Nombre = "Ariary malgache"
                        },
                        new
                        {
                            Id = 89,
                            Codigo = "MKD",
                            Nombre = "Denar macedonio"
                        },
                        new
                        {
                            Id = 90,
                            Codigo = "MMK",
                            Nombre = "Kyat birmano"
                        },
                        new
                        {
                            Id = 91,
                            Codigo = "MNT",
                            Nombre = "Tugrik mongol"
                        },
                        new
                        {
                            Id = 92,
                            Codigo = "MOP",
                            Nombre = "Pataca de Macao"
                        },
                        new
                        {
                            Id = 93,
                            Codigo = "MRO",
                            Nombre = "Uguiya"
                        },
                        new
                        {
                            Id = 94,
                            Codigo = "MUR",
                            Nombre = "Rupia mauriciana"
                        },
                        new
                        {
                            Id = 95,
                            Codigo = "MVR",
                            Nombre = "Rupia de Maldivas"
                        },
                        new
                        {
                            Id = 96,
                            Codigo = "MWK",
                            Nombre = "Kwacha malauí"
                        },
                        new
                        {
                            Id = 97,
                            Codigo = "MXN",
                            Nombre = "Peso mexicano"
                        },
                        new
                        {
                            Id = 98,
                            Codigo = "MYR",
                            Nombre = "Ringgit malayo"
                        },
                        new
                        {
                            Id = 99,
                            Codigo = "MZN",
                            Nombre = "Metical mozambiqueño"
                        },
                        new
                        {
                            Id = 100,
                            Codigo = "NAD",
                            Nombre = "Dólar namibio"
                        },
                        new
                        {
                            Id = 101,
                            Codigo = "NGN",
                            Nombre = "Naira nigeriano"
                        },
                        new
                        {
                            Id = 102,
                            Codigo = "NIO",
                            Nombre = "Córdoba nicaragüense"
                        },
                        new
                        {
                            Id = 103,
                            Codigo = "NOK",
                            Nombre = "Corona noruega"
                        },
                        new
                        {
                            Id = 104,
                            Codigo = "NPR",
                            Nombre = "Rupia nepalí"
                        },
                        new
                        {
                            Id = 105,
                            Codigo = "NZD",
                            Nombre = "Dólar neozelandés"
                        },
                        new
                        {
                            Id = 106,
                            Codigo = "OMR",
                            Nombre = "Rial omaní"
                        },
                        new
                        {
                            Id = 107,
                            Codigo = "PAB",
                            Nombre = "Balboa panameño"
                        },
                        new
                        {
                            Id = 108,
                            Codigo = "PEN",
                            Nombre = "Nuevo sol peruano"
                        },
                        new
                        {
                            Id = 109,
                            Codigo = "PGK",
                            Nombre = "Kina de Papúa Nueva Guinea"
                        },
                        new
                        {
                            Id = 110,
                            Codigo = "PHP",
                            Nombre = "Peso filipino"
                        },
                        new
                        {
                            Id = 111,
                            Codigo = "PKR",
                            Nombre = "Rupia pakistaní"
                        },
                        new
                        {
                            Id = 112,
                            Codigo = "PLN",
                            Nombre = "Zloty polaco"
                        },
                        new
                        {
                            Id = 113,
                            Codigo = "PYG",
                            Nombre = "Guaraní paraguayo"
                        },
                        new
                        {
                            Id = 114,
                            Codigo = "QAR",
                            Nombre = "Riyal qatarí"
                        },
                        new
                        {
                            Id = 115,
                            Codigo = "RON",
                            Nombre = "Leu rumano"
                        },
                        new
                        {
                            Id = 116,
                            Codigo = "RSD",
                            Nombre = "Dinar serbio"
                        },
                        new
                        {
                            Id = 117,
                            Codigo = "RUB",
                            Nombre = "Rublo ruso"
                        },
                        new
                        {
                            Id = 118,
                            Codigo = "RWF",
                            Nombre = "Franco ruandés"
                        },
                        new
                        {
                            Id = 119,
                            Codigo = "SAR",
                            Nombre = "Riyal saudí"
                        },
                        new
                        {
                            Id = 120,
                            Codigo = "SBD",
                            Nombre = "Dólar de las Islas Salomón"
                        },
                        new
                        {
                            Id = 121,
                            Codigo = "SCR",
                            Nombre = "Rupia de Seychelles"
                        },
                        new
                        {
                            Id = 122,
                            Codigo = "SDG",
                            Nombre = "Libra sudanesa"
                        },
                        new
                        {
                            Id = 123,
                            Codigo = "SEK",
                            Nombre = "Corona sueca"
                        },
                        new
                        {
                            Id = 124,
                            Codigo = "SGD",
                            Nombre = "Dólar de Singapur"
                        },
                        new
                        {
                            Id = 125,
                            Codigo = "SHP",
                            Nombre = "Libra de Santa Elena"
                        },
                        new
                        {
                            Id = 126,
                            Codigo = "SLL",
                            Nombre = "Leone de Sierra Leona"
                        },
                        new
                        {
                            Id = 127,
                            Codigo = "SOS",
                            Nombre = "Chelín somalí"
                        },
                        new
                        {
                            Id = 128,
                            Codigo = "SRD",
                            Nombre = "Dólar surinamés"
                        },
                        new
                        {
                            Id = 129,
                            Codigo = "STD",
                            Nombre = "Dobra de Santo Tomé y Príncipe"
                        },
                        new
                        {
                            Id = 130,
                            Codigo = "SVC",
                            Nombre = "Colón salvadoreño"
                        },
                        new
                        {
                            Id = 131,
                            Codigo = "SYP",
                            Nombre = "Libra siria"
                        },
                        new
                        {
                            Id = 132,
                            Codigo = "SZL",
                            Nombre = "Lilangeni de Suazilandia"
                        },
                        new
                        {
                            Id = 133,
                            Codigo = "THB",
                            Nombre = "Baht tailandés"
                        },
                        new
                        {
                            Id = 134,
                            Codigo = "TJS",
                            Nombre = "Somoni tayiko"
                        },
                        new
                        {
                            Id = 135,
                            Codigo = "TMT",
                            Nombre = "Manat turcomano"
                        },
                        new
                        {
                            Id = 136,
                            Codigo = "TND",
                            Nombre = "Dinar tunecino"
                        },
                        new
                        {
                            Id = 137,
                            Codigo = "TOP",
                            Nombre = "Paʻanga tongano"
                        },
                        new
                        {
                            Id = 138,
                            Codigo = "TRY",
                            Nombre = "Lira turca"
                        },
                        new
                        {
                            Id = 139,
                            Codigo = "TTD",
                            Nombre = "Dólar de Trinidad y Tobago"
                        },
                        new
                        {
                            Id = 140,
                            Codigo = "TWD",
                            Nombre = "Nuevo dólar taiwanés"
                        },
                        new
                        {
                            Id = 141,
                            Codigo = "TZS",
                            Nombre = "Chelín tanzano"
                        },
                        new
                        {
                            Id = 142,
                            Codigo = "UAH",
                            Nombre = "Grivna ucraniana"
                        },
                        new
                        {
                            Id = 143,
                            Codigo = "UGX",
                            Nombre = "Chelín ugandés"
                        },
                        new
                        {
                            Id = 144,
                            Codigo = "USD",
                            Nombre = "Dólar estadounidense"
                        },
                        new
                        {
                            Id = 145,
                            Codigo = "UYU",
                            Nombre = "Peso uruguayo"
                        },
                        new
                        {
                            Id = 146,
                            Codigo = "UZS",
                            Nombre = "Som uzbeko"
                        },
                        new
                        {
                            Id = 147,
                            Codigo = "VEF",
                            Nombre = "Bolívar venezolano"
                        },
                        new
                        {
                            Id = 148,
                            Codigo = "VND",
                            Nombre = "Dong vietnamita"
                        },
                        new
                        {
                            Id = 149,
                            Codigo = "VUV",
                            Nombre = "Vatu vanuatuense"
                        },
                        new
                        {
                            Id = 150,
                            Codigo = "WST",
                            Nombre = "Samoano tala"
                        },
                        new
                        {
                            Id = 151,
                            Codigo = "XAF",
                            Nombre = "Franco CFA BEAC"
                        },
                        new
                        {
                            Id = 152,
                            Codigo = "XCD",
                            Nombre = "Dólar del Caribe Oriental"
                        },
                        new
                        {
                            Id = 153,
                            Codigo = "XOF",
                            Nombre = "Franco CFA de África Occidental"
                        },
                        new
                        {
                            Id = 154,
                            Codigo = "XPF",
                            Nombre = "Franco CFP"
                        },
                        new
                        {
                            Id = 155,
                            Codigo = "YER",
                            Nombre = "Rial yemení"
                        },
                        new
                        {
                            Id = 156,
                            Codigo = "ZAR",
                            Nombre = "Rand sudafricano"
                        },
                        new
                        {
                            Id = 157,
                            Codigo = "ZMW",
                            Nombre = "Kwacha zambiano"
                        },
                        new
                        {
                            Id = 158,
                            Codigo = "ZWL",
                            Nombre = "Dólar zimbabuense"
                        },
                        new
                        {
                            Id = 159,
                            Codigo = "BTC",
                            Nombre = "Bitcoin"
                        },
                        new
                        {
                            Id = 160,
                            Codigo = "ETH",
                            Nombre = "Ethereum"
                        },
                        new
                        {
                            Id = 161,
                            Codigo = "BNB",
                            Nombre = "Binance"
                        },
                        new
                        {
                            Id = 162,
                            Codigo = "XRP",
                            Nombre = "Ripple"
                        },
                        new
                        {
                            Id = 163,
                            Codigo = "SOL",
                            Nombre = "Solana"
                        },
                        new
                        {
                            Id = 164,
                            Codigo = "DOT",
                            Nombre = "Polkadot"
                        },
                        new
                        {
                            Id = 165,
                            Codigo = "AVAX",
                            Nombre = "Avalanche"
                        },
                        new
                        {
                            Id = 166,
                            Codigo = "MATIC",
                            Nombre = "Matic Token"
                        },
                        new
                        {
                            Id = 167,
                            Codigo = "LTC",
                            Nombre = "Litecoin"
                        },
                        new
                        {
                            Id = 168,
                            Codigo = "ADA",
                            Nombre = "Cardano"
                        },
                        new
                        {
                            Id = 169,
                            Codigo = "USDT",
                            Nombre = "Tether"
                        },
                        new
                        {
                            Id = 170,
                            Codigo = "USDC",
                            Nombre = "USD Coin"
                        },
                        new
                        {
                            Id = 171,
                            Codigo = "DAI",
                            Nombre = "Dai"
                        },
                        new
                        {
                            Id = 172,
                            Codigo = "ARB",
                            Nombre = "Arbitrum"
                        },
                        new
                        {
                            Id = 173,
                            Codigo = "OP",
                            Nombre = "Optimism"
                        },
                        new
                        {
                            Id = 174,
                            Codigo = "VES",
                            Nombre = "Bolívar venezolano"
                        },
                        new
                        {
                            Id = 175,
                            Codigo = "STN",
                            Nombre = "Dobra de Santo Tomé y Príncipe"
                        },
                        new
                        {
                            Id = 176,
                            Codigo = "MRU",
                            Nombre = "Uguiya mauritana"
                        });
                });

            modelBuilder.Entity("Servidor.Dominio.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MonedaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MonedaId");

                    b.ToTable("Paises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "AE",
                            MonedaId = 1,
                            Nombre = "Emiratos Árabes Unidos"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "AF",
                            MonedaId = 2,
                            Nombre = "Afganistán"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "AL",
                            MonedaId = 3,
                            Nombre = "Albania"
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "AM",
                            MonedaId = 4,
                            Nombre = "Armenia"
                        },
                        new
                        {
                            Id = 5,
                            Codigo = "CW",
                            MonedaId = 5,
                            Nombre = "Curazao"
                        },
                        new
                        {
                            Id = 6,
                            Codigo = "SX",
                            MonedaId = 5,
                            Nombre = "San Martín"
                        },
                        new
                        {
                            Id = 7,
                            Codigo = "AO",
                            MonedaId = 6,
                            Nombre = "Angola"
                        },
                        new
                        {
                            Id = 8,
                            Codigo = "AR",
                            MonedaId = 7,
                            Nombre = "Argentina"
                        },
                        new
                        {
                            Id = 9,
                            Codigo = "AU",
                            MonedaId = 8,
                            Nombre = "Australia"
                        },
                        new
                        {
                            Id = 10,
                            Codigo = "CC",
                            MonedaId = 8,
                            Nombre = "Islas Cocos"
                        },
                        new
                        {
                            Id = 11,
                            Codigo = "CX",
                            MonedaId = 8,
                            Nombre = "Isla de Pascua"
                        },
                        new
                        {
                            Id = 12,
                            Codigo = "HM",
                            MonedaId = 8,
                            Nombre = "Islas Heard y McDonald"
                        },
                        new
                        {
                            Id = 13,
                            Codigo = "KI",
                            MonedaId = 8,
                            Nombre = "Kiribati"
                        },
                        new
                        {
                            Id = 14,
                            Codigo = "NF",
                            MonedaId = 8,
                            Nombre = "Isla Norfolk"
                        },
                        new
                        {
                            Id = 15,
                            Codigo = "NR",
                            MonedaId = 8,
                            Nombre = "Nauru"
                        },
                        new
                        {
                            Id = 16,
                            Codigo = "TV",
                            MonedaId = 8,
                            Nombre = "Tuvalu"
                        },
                        new
                        {
                            Id = 17,
                            Codigo = "AW",
                            MonedaId = 9,
                            Nombre = "Aruba"
                        },
                        new
                        {
                            Id = 18,
                            Codigo = "AZ",
                            MonedaId = 10,
                            Nombre = "Azerbaiyán"
                        },
                        new
                        {
                            Id = 19,
                            Codigo = "BA",
                            MonedaId = 11,
                            Nombre = "Bosnia y Herzegovina"
                        },
                        new
                        {
                            Id = 20,
                            Codigo = "BB",
                            MonedaId = 12,
                            Nombre = "Barbados"
                        },
                        new
                        {
                            Id = 21,
                            Codigo = "BD",
                            MonedaId = 13,
                            Nombre = "Bangladesh"
                        },
                        new
                        {
                            Id = 22,
                            Codigo = "BG",
                            MonedaId = 14,
                            Nombre = "Bulgaria"
                        },
                        new
                        {
                            Id = 23,
                            Codigo = "BH",
                            MonedaId = 15,
                            Nombre = "Baréin"
                        },
                        new
                        {
                            Id = 24,
                            Codigo = "BI",
                            MonedaId = 16,
                            Nombre = "Burundi"
                        },
                        new
                        {
                            Id = 25,
                            Codigo = "BM",
                            MonedaId = 17,
                            Nombre = "Bermuda"
                        },
                        new
                        {
                            Id = 26,
                            Codigo = "BN",
                            MonedaId = 18,
                            Nombre = "Brunei"
                        },
                        new
                        {
                            Id = 27,
                            Codigo = "BO",
                            MonedaId = 19,
                            Nombre = "Bolivia"
                        },
                        new
                        {
                            Id = 28,
                            Codigo = "BR",
                            MonedaId = 20,
                            Nombre = "Brasil"
                        },
                        new
                        {
                            Id = 29,
                            Codigo = "BS",
                            MonedaId = 21,
                            Nombre = "Bahamas"
                        },
                        new
                        {
                            Id = 30,
                            Codigo = "BT",
                            MonedaId = 22,
                            Nombre = "Bután"
                        },
                        new
                        {
                            Id = 31,
                            Codigo = "BW",
                            MonedaId = 23,
                            Nombre = "Botsuana"
                        },
                        new
                        {
                            Id = 32,
                            Codigo = "ZW",
                            MonedaId = 23,
                            Nombre = "Zimbabue"
                        },
                        new
                        {
                            Id = 33,
                            Codigo = "BY",
                            MonedaId = 24,
                            Nombre = "Bielorrusia"
                        },
                        new
                        {
                            Id = 34,
                            Codigo = "BZ",
                            MonedaId = 25,
                            Nombre = "Belice"
                        },
                        new
                        {
                            Id = 35,
                            Codigo = "CA",
                            MonedaId = 26,
                            Nombre = "Canadá"
                        },
                        new
                        {
                            Id = 36,
                            Codigo = "CD",
                            MonedaId = 27,
                            Nombre = "República Democrática del Congo"
                        },
                        new
                        {
                            Id = 37,
                            Codigo = "CH",
                            MonedaId = 28,
                            Nombre = "Suiza"
                        },
                        new
                        {
                            Id = 38,
                            Codigo = "LI",
                            MonedaId = 28,
                            Nombre = "Liechtenstein"
                        },
                        new
                        {
                            Id = 39,
                            Codigo = "CL",
                            MonedaId = 30,
                            Nombre = "Chile"
                        },
                        new
                        {
                            Id = 40,
                            Codigo = "CN",
                            MonedaId = 31,
                            Nombre = "China"
                        },
                        new
                        {
                            Id = 41,
                            Codigo = "CO",
                            MonedaId = 32,
                            Nombre = "Colombia"
                        },
                        new
                        {
                            Id = 42,
                            Codigo = "CR",
                            MonedaId = 33,
                            Nombre = "Costa Rica"
                        },
                        new
                        {
                            Id = 43,
                            Codigo = "CU",
                            MonedaId = 35,
                            Nombre = "Cuba"
                        },
                        new
                        {
                            Id = 44,
                            Codigo = "CV",
                            MonedaId = 36,
                            Nombre = "Cabo Verde"
                        },
                        new
                        {
                            Id = 45,
                            Codigo = "CZ",
                            MonedaId = 37,
                            Nombre = "República Checa"
                        },
                        new
                        {
                            Id = 46,
                            Codigo = "DJ",
                            MonedaId = 38,
                            Nombre = "Yibuti"
                        },
                        new
                        {
                            Id = 47,
                            Codigo = "DK",
                            MonedaId = 39,
                            Nombre = "Dinamarca"
                        },
                        new
                        {
                            Id = 48,
                            Codigo = "FO",
                            MonedaId = 39,
                            Nombre = "Islas Faroe"
                        },
                        new
                        {
                            Id = 49,
                            Codigo = "GL",
                            MonedaId = 39,
                            Nombre = "Groenlandia"
                        },
                        new
                        {
                            Id = 50,
                            Codigo = "DO",
                            MonedaId = 40,
                            Nombre = "República Dominicana"
                        },
                        new
                        {
                            Id = 51,
                            Codigo = "DZ",
                            MonedaId = 41,
                            Nombre = "Argelia"
                        },
                        new
                        {
                            Id = 52,
                            Codigo = "EG",
                            MonedaId = 42,
                            Nombre = "Egipto"
                        },
                        new
                        {
                            Id = 53,
                            Codigo = "PS",
                            MonedaId = 42,
                            Nombre = "Territorios Palestinos"
                        },
                        new
                        {
                            Id = 54,
                            Codigo = "ER",
                            MonedaId = 43,
                            Nombre = "Eritrea"
                        },
                        new
                        {
                            Id = 55,
                            Codigo = "ET",
                            MonedaId = 44,
                            Nombre = "Etiopía"
                        },
                        new
                        {
                            Id = 56,
                            Codigo = "AD",
                            MonedaId = 45,
                            Nombre = "Andorra"
                        },
                        new
                        {
                            Id = 57,
                            Codigo = "AT",
                            MonedaId = 45,
                            Nombre = "Austria"
                        },
                        new
                        {
                            Id = 58,
                            Codigo = "AX",
                            MonedaId = 45,
                            Nombre = "Åland"
                        },
                        new
                        {
                            Id = 59,
                            Codigo = "BE",
                            MonedaId = 45,
                            Nombre = "Bélgica"
                        },
                        new
                        {
                            Id = 60,
                            Codigo = "BL",
                            MonedaId = 45,
                            Nombre = "San Bartolomé"
                        },
                        new
                        {
                            Id = 61,
                            Codigo = "CP",
                            MonedaId = 45,
                            Nombre = "Clipperton"
                        },
                        new
                        {
                            Id = 62,
                            Codigo = "CY",
                            MonedaId = 45,
                            Nombre = "Chipre"
                        },
                        new
                        {
                            Id = 63,
                            Codigo = "DE",
                            MonedaId = 45,
                            Nombre = "Alemania"
                        },
                        new
                        {
                            Id = 64,
                            Codigo = "EA",
                            MonedaId = 45,
                            Nombre = "Ceuta y Melilla"
                        },
                        new
                        {
                            Id = 65,
                            Codigo = "EE",
                            MonedaId = 45,
                            Nombre = "Estonia"
                        },
                        new
                        {
                            Id = 66,
                            Codigo = "ES",
                            MonedaId = 45,
                            Nombre = "España"
                        },
                        new
                        {
                            Id = 67,
                            Codigo = "FI",
                            MonedaId = 45,
                            Nombre = "Finlandia"
                        },
                        new
                        {
                            Id = 68,
                            Codigo = "FR",
                            MonedaId = 45,
                            Nombre = "Francia"
                        },
                        new
                        {
                            Id = 69,
                            Codigo = "FX",
                            MonedaId = 45,
                            Nombre = "Francia metropolitana"
                        },
                        new
                        {
                            Id = 70,
                            Codigo = "GF",
                            MonedaId = 45,
                            Nombre = "Guayana Francesa"
                        },
                        new
                        {
                            Id = 71,
                            Codigo = "GP",
                            MonedaId = 45,
                            Nombre = "Guadalupe"
                        },
                        new
                        {
                            Id = 72,
                            Codigo = "GR",
                            MonedaId = 45,
                            Nombre = "Grecia"
                        },
                        new
                        {
                            Id = 73,
                            Codigo = "IC",
                            MonedaId = 45,
                            Nombre = "Islas Canarias"
                        },
                        new
                        {
                            Id = 74,
                            Codigo = "IE",
                            MonedaId = 45,
                            Nombre = "Irlanda"
                        },
                        new
                        {
                            Id = 75,
                            Codigo = "IT",
                            MonedaId = 45,
                            Nombre = "Italia"
                        },
                        new
                        {
                            Id = 76,
                            Codigo = "LT",
                            MonedaId = 45,
                            Nombre = "Lituania"
                        },
                        new
                        {
                            Id = 77,
                            Codigo = "LU",
                            MonedaId = 45,
                            Nombre = "Luxemburgo"
                        },
                        new
                        {
                            Id = 78,
                            Codigo = "LV",
                            MonedaId = 45,
                            Nombre = "Letonia"
                        },
                        new
                        {
                            Id = 79,
                            Codigo = "MC",
                            MonedaId = 45,
                            Nombre = "Mónaco"
                        },
                        new
                        {
                            Id = 80,
                            Codigo = "ME",
                            MonedaId = 45,
                            Nombre = "Montenegro"
                        },
                        new
                        {
                            Id = 81,
                            Codigo = "MF",
                            MonedaId = 45,
                            Nombre = "San Martín"
                        },
                        new
                        {
                            Id = 82,
                            Codigo = "MQ",
                            MonedaId = 45,
                            Nombre = "Martinica"
                        },
                        new
                        {
                            Id = 83,
                            Codigo = "MT",
                            MonedaId = 45,
                            Nombre = "Malta"
                        },
                        new
                        {
                            Id = 84,
                            Codigo = "NL",
                            MonedaId = 45,
                            Nombre = "Países Bajos"
                        },
                        new
                        {
                            Id = 85,
                            Codigo = "PM",
                            MonedaId = 45,
                            Nombre = "San Pedro y Miquelón"
                        },
                        new
                        {
                            Id = 86,
                            Codigo = "PT",
                            MonedaId = 45,
                            Nombre = "Portugal"
                        },
                        new
                        {
                            Id = 87,
                            Codigo = "RE",
                            MonedaId = 45,
                            Nombre = "Reunión"
                        },
                        new
                        {
                            Id = 88,
                            Codigo = "SI",
                            MonedaId = 45,
                            Nombre = "Eslovenia"
                        },
                        new
                        {
                            Id = 89,
                            Codigo = "SK",
                            MonedaId = 45,
                            Nombre = "Eslovaquia"
                        },
                        new
                        {
                            Id = 90,
                            Codigo = "SM",
                            MonedaId = 45,
                            Nombre = "San Marino"
                        },
                        new
                        {
                            Id = 91,
                            Codigo = "TF",
                            MonedaId = 45,
                            Nombre = "Territorios Australes y Antárticas Franceses"
                        },
                        new
                        {
                            Id = 92,
                            Codigo = "VA",
                            MonedaId = 45,
                            Nombre = "Ciudad del Vaticano"
                        },
                        new
                        {
                            Id = 93,
                            Codigo = "XK",
                            MonedaId = 45,
                            Nombre = "Kosovo"
                        },
                        new
                        {
                            Id = 94,
                            Codigo = "YT",
                            MonedaId = 45,
                            Nombre = "Mayotte"
                        },
                        new
                        {
                            Id = 95,
                            Codigo = "FJ",
                            MonedaId = 46,
                            Nombre = "Fiyi"
                        },
                        new
                        {
                            Id = 96,
                            Codigo = "FK",
                            MonedaId = 47,
                            Nombre = "Islas Malvinas"
                        },
                        new
                        {
                            Id = 97,
                            Codigo = "GB",
                            MonedaId = 48,
                            Nombre = "Reino Unido"
                        },
                        new
                        {
                            Id = 98,
                            Codigo = "UK",
                            MonedaId = 48,
                            Nombre = "Reino Unido"
                        });
                });

            modelBuilder.Entity("Servidor.Dominio.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PaisId")
                        .HasColumnType("integer");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Servidor.Dominio.Alerta", b =>
                {
                    b.HasOne("Servidor.Dominio.Moneda", "Moneda")
                        .WithMany()
                        .HasForeignKey("MonedaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Servidor.Dominio.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Moneda");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Servidor.Dominio.Cotizacion", b =>
                {
                    b.HasOne("Servidor.Dominio.Moneda", "MonedaBase")
                        .WithMany("Cotizaciones")
                        .HasForeignKey("MonedaBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonedaBase");
                });

            modelBuilder.Entity("Servidor.Dominio.Pais", b =>
                {
                    b.HasOne("Servidor.Dominio.Moneda", "Moneda")
                        .WithMany("Paises")
                        .HasForeignKey("MonedaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Moneda");
                });

            modelBuilder.Entity("Servidor.Dominio.Usuario", b =>
                {
                    b.HasOne("Servidor.Dominio.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Servidor.Dominio.Moneda", b =>
                {
                    b.Navigation("Cotizaciones");

                    b.Navigation("Paises");
                });
#pragma warning restore 612, 618
        }
    }
}
