using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;
using Servidor.Dominio;

namespace Servidor.Datos.Configuracion
{
    public class MonedaConfiguration: IEntityTypeConfiguration<Moneda>
        {
            public void Configure(EntityTypeBuilder<Moneda> builder)
            {
            builder.HasData(
                new Moneda { Id = 1, Codigo = "AED", Nombre = "Dirham de los Emiratos Árabes Unidos" },
                new Moneda { Id = 2, Codigo = "AFN", Nombre = "Afghani afgano" },
                new Moneda { Id = 3, Codigo = "ALL", Nombre = "Lek albanés" },
                new Moneda { Id = 4, Codigo = "AMD", Nombre = "Dram armenio" },
                new Moneda { Id = 5, Codigo = "ANG", Nombre = "Florín antillano neerlandés" },
                new Moneda { Id = 6, Codigo = "AOA", Nombre = "Kwanza angoleño" },
                new Moneda { Id = 7, Codigo = "ARS", Nombre = "Peso argentino" },
                new Moneda { Id = 8, Codigo = "AUD", Nombre = "Dólar australiano" },
                new Moneda { Id = 9, Codigo = "AWG", Nombre = "Florín arubeño" },
                new Moneda { Id = 10, Codigo = "AZN", Nombre = "Manat azerbaiyano" },
                new Moneda { Id = 11, Codigo = "BAM", Nombre = "Marco convertible de Bosnia-Herzegovina" },
                new Moneda { Id = 12, Codigo = "BBD", Nombre = "Dólar de Barbados" },
                new Moneda { Id = 13, Codigo = "BDT", Nombre = "Taka bangladesí" },
                new Moneda { Id = 14, Codigo = "BGN", Nombre = "Lev búlgaro" },
                new Moneda { Id = 15, Codigo = "BHD", Nombre = "Dinar bahreiní" },
                new Moneda { Id = 16, Codigo = "BIF", Nombre = "Franco burundés" },
                new Moneda { Id = 17, Codigo = "BMD", Nombre = "Dólar de Bermudas" },
                new Moneda { Id = 18, Codigo = "BND", Nombre = "Dólar de Brunei" },
                new Moneda { Id = 19, Codigo = "BOB", Nombre = "Boliviano" },
                new Moneda { Id = 20, Codigo = "BRL", Nombre = "Real brasileño" },
                new Moneda { Id = 21, Codigo = "BSD", Nombre = "Dólar bahameño" },
                new Moneda { Id = 22, Codigo = "BTN", Nombre = "Ngultrum butanés" },
                new Moneda { Id = 23, Codigo = "BWP", Nombre = "Pula de Botsuana" },
                new Moneda { Id = 24, Codigo = "BYN", Nombre = "Rublo bielorruso" },
                new Moneda { Id = 25, Codigo = "BZD", Nombre = "Dólar beliceño" },
                new Moneda { Id = 26, Codigo = "CAD", Nombre = "Dólar canadiense" },
                new Moneda { Id = 27, Codigo = "CDF", Nombre = "Franco congoleño" },
                new Moneda { Id = 28, Codigo = "CHF", Nombre = "Franco suizo" },
                new Moneda { Id = 29, Codigo = "CLF", Nombre = "Unidad de Fomento" },
                new Moneda { Id = 30, Codigo = "CLP", Nombre = "Peso chileno" },
                new Moneda { Id = 31, Codigo = "CNY", Nombre = "Yuan chino" },
                new Moneda { Id = 32, Codigo = "COP", Nombre = "Peso colombiano" },
                new Moneda { Id = 33, Codigo = "CRC", Nombre = "Colón costarricense" },
                new Moneda { Id = 34, Codigo = "CUC", Nombre = "Peso convertible cubano" },
                new Moneda { Id = 35, Codigo = "CUP", Nombre = "Peso cubano" },
                new Moneda { Id = 36, Codigo = "CVE", Nombre = "Escudo caboverdiano" },
                new Moneda { Id = 37, Codigo = "CZK", Nombre = "Corona checa" },
                new Moneda { Id = 38, Codigo = "DJF", Nombre = "Franco de Yibuti" },
                new Moneda { Id = 39, Codigo = "DKK", Nombre = "Corona danesa" },
                new Moneda { Id = 40, Codigo = "DOP", Nombre = "Peso dominicano" },
                new Moneda { Id = 41, Codigo = "DZD", Nombre = "Dinar argelino" },
                new Moneda { Id = 42, Codigo = "EGP", Nombre = "Libra egipcia" },
                new Moneda { Id = 43, Codigo = "ERN", Nombre = "'Nakfa eritrea" },
                new Moneda { Id = 44, Codigo = "ETB", Nombre = "Birr etíope" },
                new Moneda { Id = 45, Codigo = "EUR", Nombre = "Euro" },
                new Moneda { Id = 46, Codigo = "FJD", Nombre = "óDlar fiyiano" },
                new Moneda { Id = 47, Codigo = "FKP", Nombre = "Libra de las Islas Malvinas" },
                new Moneda { Id = 48, Codigo = "GBP", Nombre = "Libra esterlina británica" },
                new Moneda { Id = 49, Codigo = "GEL", Nombre = "Lari georgiano" },
                new Moneda { Id = 50, Codigo = "GGP", Nombre = "Libra de Guernsey" },
                new Moneda { Id = 51, Codigo = "GHS", Nombre = "Cedi ghanés" },
                new Moneda { Id = 52, Codigo = "GIP", Nombre = "Libra de Gibraltar" },
                new Moneda { Id = 53, Codigo = "GMD", Nombre = "Dalasi gambiano" },
                new Moneda { Id = 54, Codigo = "GNF", Nombre = "Franco guineano" },
                new Moneda { Id = 55, Codigo = "GTQ", Nombre = "Quetzal guatemalteco" },
                new Moneda { Id = 56, Codigo = "GYD", Nombre = "Dólar guyanés" },
                new Moneda { Id = 57, Codigo = "HKD", Nombre = "Dólar de Hong Kong" },
                new Moneda { Id = 58, Codigo = "HNL", Nombre = "Lempira hondureño" },
                new Moneda { Id = 59, Codigo = "HRK", Nombre = "Kuna croata" },
                new Moneda { Id = 60, Codigo = "HTG", Nombre = "Gourde haitiano" },
                new Moneda { Id = 61, Codigo = "HUF", Nombre = "Forint húngaro" },
                new Moneda { Id = 62, Codigo = "IDR", Nombre = "Rupia indonesia" },
                new Moneda { Id = 63, Codigo = "ILS", Nombre = "Nuevo séquel israelí" },
                new Moneda { Id = 64, Codigo = "INR", Nombre = "Rupia india" },
                new Moneda { Id = 65, Codigo = "IQD", Nombre = "Dinar iraquí" },
                new Moneda { Id = 66, Codigo = "IRR", Nombre = "Rial iraní" },
                new Moneda { Id = 67, Codigo = "ISK", Nombre = "Corona islandesa" },
                new Moneda { Id = 68, Codigo = "JMD", Nombre = "Dólar jamaiquino" },
                new Moneda { Id = 69, Codigo = "JOD", Nombre = "Dinar jordano" },
                new Moneda { Id = 70, Codigo = "JPY", Nombre = "Yen japonés" },
                new Moneda { Id = 71, Codigo = "KES", Nombre = "Chelín keniano" },
                new Moneda { Id = 72, Codigo = "KGS", Nombre = "Som kirguís" },
                new Moneda { Id = 73, Codigo = "KHR", Nombre = "Riel camboyano" },
                new Moneda { Id = 74, Codigo = "KMF", Nombre = "Franco comorense" },
                new Moneda { Id = 75, Codigo = "KPW", Nombre = "Won norcoreano" },
                new Moneda { Id = 76, Codigo = "KRW", Nombre = "Won surcoreano" },
                new Moneda { Id = 77, Codigo = "KWD", Nombre = "Dinar kuwaití" },
                new Moneda { Id = 78, Codigo = "KYD", Nombre = "Dólar de las Islas Caimán" },
                new Moneda { Id = 79, Codigo = "KZT", Nombre = "Tenge kazajo" },
                new Moneda { Id = 80, Codigo = "LAK", Nombre = "Kip laosiano" },
                new Moneda { Id = 81, Codigo = "LBP", Nombre = "Libra libanesa" },
                new Moneda { Id = 82, Codigo = "LKR", Nombre = "Rupia de Sri Lanka" },
                new Moneda { Id = 83, Codigo = "LRD", Nombre = "Dólar liberiano" },
                new Moneda { Id = 84, Codigo = "LSL", Nombre = "Loti de Lesoto" },
                new Moneda { Id = 85, Codigo = "LYD", Nombre = "Dinar libio" },
                new Moneda { Id = 86, Codigo = "MAD", Nombre = "Dirham marroquí" },
                new Moneda { Id = 87, Codigo = "MDL", Nombre = "Leu moldavo" },
                new Moneda { Id = 88, Codigo = "MGA", Nombre = "Ariary malgache" },
                new Moneda { Id = 89, Codigo = "MKD", Nombre = "Denar macedonio" },
                new Moneda { Id = 90, Codigo = "MMK", Nombre = "Kyat birmano" },
                new Moneda { Id = 91, Codigo = "MNT", Nombre = "Tugrik mongol" },
                new Moneda { Id = 92, Codigo = "MOP", Nombre = "Pataca de Macao" },
                new Moneda { Id = 93, Codigo = "MRO", Nombre = "Uguiya" },
                new Moneda { Id = 94, Codigo = "MUR", Nombre = "Rupia mauriciana" },
                new Moneda { Id = 95, Codigo = "MVR", Nombre = "Rupia de Maldivas" },
                new Moneda { Id = 96, Codigo = "MWK", Nombre = "Kwacha malauí" },
                new Moneda { Id = 97, Codigo = "MXN", Nombre = "Peso mexicano" },
                new Moneda { Id = 98, Codigo = "MYR", Nombre = "Ringgit malayo" },
                new Moneda { Id = 99, Codigo = "MZN", Nombre = "Metical mozambiqueño" },
                new Moneda { Id = 100, Codigo = "NAD", Nombre = "Dólar namibio" },
                new Moneda { Id = 101, Codigo = "NGN", Nombre = "Naira nigeriano" },
                new Moneda { Id = 102, Codigo = "NIO", Nombre = "Córdoba nicaragüense" },
                new Moneda { Id = 103, Codigo = "NOK", Nombre = "Corona noruega" },
                new Moneda { Id = 104, Codigo = "NPR", Nombre = "Rupia nepalí" },
                new Moneda { Id = 105, Codigo = "NZD", Nombre = "Dólar neozelandés" },
                new Moneda { Id = 106, Codigo = "OMR", Nombre = "Rial omaní" },
                new Moneda { Id = 107, Codigo = "PAB", Nombre = "Balboa panameño" },
                new Moneda { Id = 108, Codigo = "PEN", Nombre = "Nuevo sol peruano" },
                new Moneda { Id = 109, Codigo = "PGK", Nombre = "Kina de Papúa Nueva Guinea" },
                new Moneda { Id = 110, Codigo = "PHP", Nombre = "Peso filipino" },
                new Moneda { Id = 111, Codigo = "PKR", Nombre = "Rupia pakistaní" },
                new Moneda { Id = 112, Codigo = "PLN", Nombre = "Zloty polaco" },
                new Moneda { Id = 113, Codigo = "PYG", Nombre = "Guaraní paraguayo" },
                new Moneda { Id = 114, Codigo = "QAR", Nombre = "Riyal qatarí" },
                new Moneda { Id = 115, Codigo = "RON", Nombre = "Leu rumano" },
                new Moneda { Id = 116, Codigo = "RSD", Nombre = "Dinar serbio" },
                new Moneda { Id = 117, Codigo = "RUB", Nombre = "Rublo ruso" },
                new Moneda { Id = 118, Codigo = "RWF", Nombre = "Franco ruandés" },
                new Moneda { Id = 119, Codigo = "SAR", Nombre = "Riyal saudí" },
                new Moneda { Id = 120, Codigo = "SBD", Nombre = "Dólar de las Islas Salomón" },
                new Moneda { Id = 121, Codigo = "SCR", Nombre = "Rupia de Seychelles" },
                new Moneda { Id = 122, Codigo = "SDG", Nombre = "Libra sudanesa" },
                new Moneda { Id = 123, Codigo = "SEK", Nombre = "Corona sueca" },
                new Moneda { Id = 124, Codigo = "SGD", Nombre = "Dólar de Singapur" },
                new Moneda { Id = 125, Codigo = "SHP", Nombre = "Libra de Santa Elena" },
                new Moneda { Id = 126, Codigo = "SLL", Nombre = "Leone de Sierra Leona" },
                new Moneda { Id = 127, Codigo = "SOS", Nombre = "Chelín somalí" },
                new Moneda { Id = 128, Codigo = "SRD", Nombre = "Dólar surinamés" },
                new Moneda { Id = 129, Codigo = "STD", Nombre = "Dobra de Santo Tomé y Príncipe" },
                new Moneda { Id = 130, Codigo = "SVC", Nombre = "Colón salvadoreño" },
                new Moneda { Id = 131, Codigo = "SYP", Nombre = "Libra siria" },
                new Moneda { Id = 132, Codigo = "SZL", Nombre = "Lilangeni de Suazilandia" },
                new Moneda { Id = 133, Codigo = "THB", Nombre = "Baht tailandés" },
                new Moneda { Id = 134, Codigo = "TJS", Nombre = "Somoni tayiko" },
                new Moneda { Id = 135, Codigo = "TMT", Nombre = "Manat turcomano" },
                new Moneda { Id = 136, Codigo = "TND", Nombre = "Dinar tunecino" },
                new Moneda { Id = 137, Codigo = "TOP", Nombre = "Paʻanga tongano" },
                new Moneda { Id = 138, Codigo = "TRY", Nombre = "Lira turca" },
                new Moneda { Id = 139, Codigo = "TTD", Nombre = "Dólar de Trinidad y Tobago" },
                new Moneda { Id = 140, Codigo = "TWD", Nombre = "Nuevo dólar taiwanés" },
                new Moneda { Id = 141, Codigo = "TZS", Nombre = "Chelín tanzano" },
                new Moneda { Id = 142, Codigo = "UAH", Nombre = "Grivna ucraniana" },
                new Moneda { Id = 143, Codigo = "UGX", Nombre = "Chelín ugandés" },
                new Moneda { Id = 144, Codigo = "USD", Nombre = "Dólar estadounidense" },
                new Moneda { Id = 145, Codigo = "UYU", Nombre = "Peso uruguayo" },
                new Moneda { Id = 146, Codigo = "UZS", Nombre = "Som uzbeko" },
                new Moneda { Id = 147, Codigo = "VEF", Nombre = "Bolívar venezolano" },
                new Moneda { Id = 148, Codigo = "VND", Nombre = "Dong vietnamita" },
                new Moneda { Id = 149, Codigo = "VUV", Nombre = "Vatu vanuatuense" },
                new Moneda { Id = 150, Codigo = "WST", Nombre = "Samoano tala" },
                new Moneda { Id = 151, Codigo = "XAF", Nombre = "Franco CFA BEAC" },
                new Moneda { Id = 152, Codigo = "XCD", Nombre = "Dólar del Caribe Oriental" },
                new Moneda { Id = 153, Codigo = "XOF", Nombre = "Franco CFA de África Occidental" },
                new Moneda { Id = 154, Codigo = "XPF", Nombre = "Franco CFP" },
                new Moneda { Id = 155, Codigo = "YER", Nombre = "Rial yemení" },
                new Moneda { Id = 156, Codigo = "ZAR", Nombre = "Rand sudafricano" },
                new Moneda { Id = 157, Codigo = "ZMW", Nombre = "Kwacha zambiano" },
                new Moneda { Id = 158, Codigo = "ZWL", Nombre = "Dólar zimbabuense" },
                new Moneda { Id = 159, Codigo = "BTC", Nombre = "Bitcoin" },
                new Moneda { Id = 160, Codigo = "ETH", Nombre = "Ethereum" },
                new Moneda { Id = 161, Codigo = "BNB", Nombre = "Binance" },
                new Moneda { Id = 162, Codigo = "XRP", Nombre = "Ripple" },
                new Moneda { Id = 163, Codigo = "SOL", Nombre = "Solana" },
                new Moneda { Id = 164, Codigo = "DOT", Nombre = "Polkadot" },
                new Moneda { Id = 165, Codigo = "AVAX", Nombre = "Avalanche" },
                new Moneda { Id = 166, Codigo = "MATIC", Nombre = "Matic Token" },
                new Moneda { Id = 167, Codigo = "LTC", Nombre = "Litecoin" },
                new Moneda { Id = 168, Codigo = "ADA", Nombre = "Cardano" },
                new Moneda { Id = 169, Codigo = "USDT", Nombre = "Tether" },
                new Moneda { Id = 170, Codigo = "USDC", Nombre = "USD Coin" },
                new Moneda { Id = 171, Codigo = "DAI", Nombre = "Dai" },
                new Moneda { Id = 172, Codigo = "ARB", Nombre = "Arbitrum" },
                new Moneda { Id = 173, Codigo = "OP", Nombre = "Optimism" },
                new Moneda { Id = 174, Codigo = "VES", Nombre = "Bolívar venezolano" },
                new Moneda { Id = 175, Codigo = "STN", Nombre = "Dobra de Santo Tomé y Príncipe" },
                new Moneda { Id = 176, Codigo = "MRU", Nombre = "Uguiya mauritana" });
            }
        }
    }