using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Servidor.Dominio;
using System.Collections.Generic;

namespace Servidor.Datos.Configuracion
{
    public class PaisConfiguration : IEntityTypeConfiguration<Pais>
    {
        public void Configure(EntityTypeBuilder<Pais> builder)
        {
            builder.HasData(
                new Pais { Id = 1, Codigo = "AE", Nombre = "Emiratos Árabes Unidos", MonedaId = 1 },
                new Pais { Id = 2, Codigo = "AF", Nombre = "Afganistán", MonedaId = 2 },
                new Pais { Id = 3, Codigo = "AL", Nombre = "Albania", MonedaId = 3 },
                new Pais { Id = 4, Codigo = "AM", Nombre = "Armenia", MonedaId = 4 },
                new Pais { Id = 5, Codigo = "CW", Nombre = "Curazao", MonedaId = 5 },
                new Pais { Id = 6, Codigo = "SX", Nombre = "San Martín", MonedaId = 5 },
                new Pais { Id = 7, Codigo = "AO", Nombre = "Angola", MonedaId = 6 },
                new Pais { Id = 8, Codigo = "AR", Nombre = "Argentina", MonedaId = 7 },
                new Pais { Id = 9, Codigo = "AU", Nombre = "Australia", MonedaId = 8 },
                new Pais { Id = 10, Codigo = "CC", Nombre = "Islas Cocos", MonedaId = 8 },
                new Pais { Id = 11, Codigo = "CX", Nombre = "Isla de Pascua", MonedaId = 8 },
                new Pais { Id = 12, Codigo = "HM", Nombre = "Islas Heard y McDonald", MonedaId = 8 },
                new Pais { Id = 13, Codigo = "KI", Nombre = "Kiribati", MonedaId = 8 },
                new Pais { Id = 14, Codigo = "NF", Nombre = "Isla Norfolk", MonedaId = 8 },
                new Pais { Id = 15, Codigo = "NR", Nombre = "Nauru", MonedaId = 8 },
                new Pais { Id = 16, Codigo = "TV", Nombre = "Tuvalu", MonedaId = 8 },
                new Pais { Id = 17, Codigo = "AW", Nombre = "Aruba", MonedaId = 9 },
                new Pais { Id = 18, Codigo = "AZ", Nombre = "Azerbaiyán", MonedaId = 10 },
                new Pais { Id = 19, Codigo = "BA", Nombre = "Bosnia y Herzegovina", MonedaId = 11 },
                new Pais { Id = 20, Codigo = "BB", Nombre = "Barbados", MonedaId = 12 },
                new Pais { Id = 21, Codigo = "BD", Nombre = "Bangladesh", MonedaId = 13 },
                new Pais { Id = 22, Codigo = "BG", Nombre = "Bulgaria", MonedaId = 14 },
                new Pais { Id = 23, Codigo = "BH", Nombre = "Baréin", MonedaId = 15 },
                new Pais { Id = 24, Codigo = "BI", Nombre = "Burundi", MonedaId = 16 },
                new Pais { Id = 25, Codigo = "BM", Nombre = "Bermuda", MonedaId = 17 },
                new Pais { Id = 26, Codigo = "BN", Nombre = "Brunei", MonedaId = 18 },
                new Pais { Id = 27, Codigo = "BO", Nombre = "Bolivia", MonedaId = 19 },
                new Pais { Id = 28, Codigo = "BR", Nombre = "Brasil", MonedaId = 20 },
                new Pais { Id = 29, Codigo = "BS", Nombre = "Bahamas", MonedaId = 21 },
                new Pais { Id = 30, Codigo = "BT", Nombre = "Bután", MonedaId = 22 },
                new Pais { Id = 31, Codigo = "BW", Nombre = "Botsuana", MonedaId = 23 },
                new Pais { Id = 32, Codigo = "ZW", Nombre = "Zimbabue", MonedaId = 23 },
                new Pais { Id = 33, Codigo = "BY", Nombre = "Bielorrusia", MonedaId = 24 },
                new Pais { Id = 34, Codigo = "BZ", Nombre = "Belice", MonedaId = 25 },
                new Pais { Id = 35, Codigo = "CA", Nombre = "Canadá", MonedaId = 26 },
                new Pais { Id = 36, Codigo = "CD", Nombre = "República Democrática del Congo", MonedaId = 27 },
                new Pais { Id = 37, Codigo = "CH", Nombre = "Suiza", MonedaId = 28 },
                new Pais { Id = 38, Codigo = "LI", Nombre = "Liechtenstein", MonedaId = 28 },
                new Pais { Id = 39, Codigo = "CL", Nombre = "Chile", MonedaId = 30 },
                new Pais { Id = 40, Codigo = "CN", Nombre = "China", MonedaId = 31 },
                new Pais { Id = 41, Codigo = "CO", Nombre = "Colombia", MonedaId = 32 },
                new Pais { Id = 42, Codigo = "CR", Nombre = "Costa Rica", MonedaId = 33 },
                new Pais { Id = 43, Codigo = "CU", Nombre = "Cuba", MonedaId = 35 },
                new Pais { Id = 44, Codigo = "CV", Nombre = "Cabo Verde", MonedaId = 36 },
                new Pais { Id = 45, Codigo = "CZ", Nombre = "República Checa", MonedaId = 37 },
                new Pais { Id = 46, Codigo = "DJ", Nombre = "Yibuti", MonedaId = 38 },
                new Pais { Id = 47, Codigo = "DK", Nombre = "Dinamarca", MonedaId = 39 },
                new Pais { Id = 48, Codigo = "FO", Nombre = "Islas Faroe", MonedaId = 39 },
                new Pais { Id = 49, Codigo = "GL", Nombre = "Groenlandia", MonedaId = 39 },
                new Pais { Id = 50, Codigo = "DO", Nombre = "República Dominicana", MonedaId = 40 },
                new Pais { Id = 51, Codigo = "DZ", Nombre = "Argelia", MonedaId = 41 },
                new Pais { Id = 52, Codigo = "EG", Nombre = "Egipto", MonedaId = 42 },
                new Pais { Id = 53, Codigo = "PS", Nombre = "Territorios Palestinos", MonedaId = 42 },
                new Pais { Id = 54, Codigo = "ER", Nombre = "Eritrea", MonedaId = 43 },
                new Pais { Id = 55, Codigo = "ET", Nombre = "Etiopía", MonedaId = 44 },
                new Pais { Id = 56, Codigo = "AD", Nombre = "Andorra", MonedaId = 45 },
                new Pais { Id = 57, Codigo = "AT", Nombre = "Austria", MonedaId = 45 },
                new Pais { Id = 58, Codigo = "AX", Nombre = "Åland", MonedaId = 45 },
                new Pais { Id = 59, Codigo = "BE", Nombre = "Bélgica", MonedaId = 45 },
                new Pais { Id = 60, Codigo = "BL", Nombre = "San Bartolomé", MonedaId = 45 },
                new Pais { Id = 61, Codigo = "CP", Nombre = "Clipperton", MonedaId = 45 },
                new Pais { Id = 62, Codigo = "CY", Nombre = "Chipre", MonedaId = 45 },
                new Pais { Id = 63, Codigo = "DE", Nombre = "Alemania", MonedaId = 45 },
                new Pais { Id = 64, Codigo = "EA", Nombre = "Ceuta y Melilla", MonedaId = 45 },
                new Pais { Id = 65, Codigo = "EE", Nombre = "Estonia", MonedaId = 45 },
                new Pais { Id = 66, Codigo = "ES", Nombre = "España", MonedaId = 45 },
                new Pais { Id = 67, Codigo = "FI", Nombre = "Finlandia", MonedaId = 45 },
                new Pais { Id = 68, Codigo = "FR", Nombre = "Francia", MonedaId = 45 },
                new Pais { Id = 69, Codigo = "FX", Nombre = "Francia metropolitana", MonedaId = 45 },
                new Pais { Id = 70, Codigo = "GF", Nombre = "Guayana Francesa", MonedaId = 45 },
                new Pais { Id = 71, Codigo = "GP", Nombre = "Guadalupe", MonedaId = 45 },
                new Pais { Id = 72, Codigo = "GR", Nombre = "Grecia", MonedaId = 45 },
                new Pais { Id = 73, Codigo = "IC", Nombre = "Islas Canarias", MonedaId = 45 },
                new Pais { Id = 74, Codigo = "IE", Nombre = "Irlanda", MonedaId = 45 },
                new Pais { Id = 75, Codigo = "IT", Nombre = "Italia", MonedaId = 45 },
                new Pais { Id = 76, Codigo = "LT", Nombre = "Lituania", MonedaId = 45 },
                new Pais { Id = 77, Codigo = "LU", Nombre = "Luxemburgo", MonedaId = 45 },
                new Pais { Id = 78, Codigo = "LV", Nombre = "Letonia", MonedaId = 45 },
                new Pais { Id = 79, Codigo = "MC", Nombre = "Mónaco", MonedaId = 45 },
                new Pais { Id = 80, Codigo = "ME", Nombre = "Montenegro", MonedaId = 45 },
                new Pais { Id = 81, Codigo = "MF", Nombre = "San Martín", MonedaId = 45 },
                new Pais { Id = 82, Codigo = "MQ", Nombre = "Martinica", MonedaId = 45 },
                new Pais { Id = 83, Codigo = "MT", Nombre = "Malta", MonedaId = 45 },
                new Pais { Id = 84, Codigo = "NL", Nombre = "Países Bajos", MonedaId = 45 },
                new Pais { Id = 85, Codigo = "PM", Nombre = "San Pedro y Miquelón", MonedaId = 45 },
                new Pais { Id = 86, Codigo = "PT", Nombre = "Portugal", MonedaId = 45 },
                new Pais { Id = 87, Codigo = "RE", Nombre = "Reunión", MonedaId = 45 },
                new Pais { Id = 88, Codigo = "SI", Nombre = "Eslovenia", MonedaId = 45 },
                new Pais { Id = 89, Codigo = "SK", Nombre = "Eslovaquia", MonedaId = 45 },
                new Pais { Id = 90, Codigo = "SM", Nombre = "San Marino", MonedaId = 45 },
                new Pais { Id = 91, Codigo = "TF", Nombre = "Territorios Australes y Antárticas Franceses", MonedaId = 45 },
                new Pais { Id = 92, Codigo = "VA", Nombre = "Ciudad del Vaticano", MonedaId = 45 },
                new Pais { Id = 93, Codigo = "XK", Nombre = "Kosovo", MonedaId = 45 },
                new Pais { Id = 94, Codigo = "YT", Nombre = "Mayotte", MonedaId = 45 },
                new Pais { Id = 95, Codigo = "FJ", Nombre = "Fiyi", MonedaId = 46 },
                new Pais { Id = 96, Codigo = "FK", Nombre = "Islas Malvinas", MonedaId = 47 },
                new Pais { Id = 97, Codigo = "GB", Nombre = "Reino Unido", MonedaId = 48 },
                new Pais { Id = 98, Codigo = "UK", Nombre = "Reino Unido", MonedaId = 48 }
            );
        }

    }
}